
name: Build and analyze

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '~1.24.1'
        - name: Build
          run: go build -v ./...
        - name: Test
          run: go test -v -coverprofile='coverage.out' -json ./... > report.json
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@v2
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  